### ISSUE TITLE
Comment-not-bug Rate Limiting across multiple instances

### ISSUE THREAD

**Issue by LawrenceSmith1437** [martincostello/polly-rate-limiting#74]
I found your repo while researching rate limiting. 
I noticed that here, the state is stored using the in-memory store.  That works for single server apps. 
When an app is deployed in a multi-instance environments, it won't work so well.  To rate limit across load balanced instances needs a 3rd party witness to separately keep state.
Any thoughts to kick state storage out to Redis?

**Comment by martincostello** [comment]
This repo just shows how to integrate _Polly's_ implementation of rate limiting ([docs](https://github.com/App-vNext/Polly/wiki/Rate-Limit)) into an ASP.NET Core application for a simple use case. That implementation, in-turn, is inherently designed to be in-memory, and doesn't support arbitrary state stores for a fully-consistent strict rate limiting across multiple processes.

If you want to use something more extensible, there's two alternatives I can recommend:

1. [AspNetCoreRateLimit](https://github.com/stefanprodan/AspNetCoreRateLimit), which can read from [`IDistributedCache`](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/distributed) that in turn can be integrated with Redis ([docs](https://github.com/stefanprodan/AspNetCoreRateLimit/wiki/Using-Redis-as-a-distributed-counter-store)).
2. The new [rate limiting middleware](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#rate-limiting-middleware) that will ship as part of ASP.NET Core 7. This is still in-development, but I would expect it to support some sort of remote state for consumed limits (either in-box or via extensibility) by the time it ships in November 2022.

**Comment by LawrenceSmith1437** [comment]
Ah, I didn't know about the forthcoming facility in .Net 7. Thanks for that.  Cheers mate!

**Comment by martincostello** [comment]
For a Redis-backed implementation in .NET 7, you might want to track this issue: https://github.com/dotnet/aspnetcore/issues/41861
